stop_words_nltk = {"you'll", 'itself', 'weren', "weren't", 'nor', 'both', 'her', 'and', 'them', 'because', 'ourselves',
                   "don't", 'mightn', "that'll", 'over', 'ma', 'shouldn', 'me', 'hadn', 'mustn', 'no', 'your', 'did',
                   'haven', 'then', 'they', 'hers', 'at', 'by', 'during', 'these', 'very', 'on', 'own', 'too', "shan't",
                   'here', 'd', 'there', 'only', 'been', "couldn't", 'be', 'having', "needn't", 'm', 'but', 'under',
                   'each', 'more', 'now', "you're", 'other', "mightn't", 'all', 'will', 'i', 'she', "shouldn't", 'a',
                   'if', 'we', 'of', "you've", 'up', "doesn't", "mustn't", 'ain', 'won', 'was', 'further', 'yourself',
                   "won't", 'should', 'out', 'wouldn', "it's", 'off', 'its', "you'd", 'or', 'same', 'myself', 'those',
                   'am', 'have', 'don', 'o', "hasn't", 'himself', 'after', 'ours', 'against', 'about', 'needn', 'you',
                   'wasn', "should've", 'does', 'shan', 'our', 'not', 'hasn', 'until', "wouldn't", 'has', "hadn't",
                   'some', 'it', 'between', 'this', 'down', 'is', "wasn't", 'aren', 'in', 'yours', 'being', 'are',
                   'such', "she's", 'with', 'an', 'doesn', 'through', 'before', 'any', 'again', 'do', "haven't",
                   'doing', 'him', 'to', 'had', 'their', 'll', 'herself', 'my', 't', 'the', 'y', 'from', 've', 's',
                   "aren't", "didn't", 'yourselves', 'can', 'couldn', 'above', 'didn', 'which', 'few', 're',
                   'themselves', 'than', 'he', 'were', 'that', 'just', 'most', 'his', "isn't", 'while', 'so', 'below',
                   'theirs', 'isn', 'as', 'once', 'for', 'into'}
stop_words_spacy = {'mine', 'nor', 'both', "'d", 'therein', 'enough', 'whole', 'get', 'at', 'hereafter', 'herein', "'m",
                    'there', 'three', 'been', 'hereby', 'be', 'ever', 'cannot', 'under', 'first', 'however', 'already',
                    'latter', 'i', 'less', 'a', 'call', 'of', 'hence', "'ll", 'should', 'nothing', 'its',
                    'nevertheless', 'same', 'myself', 'beside', 'former', 'whom', 'himself', 'anyhow', 'against',
                    'empty', 'what', 'every', 'you', 'n‘t', 'please', 'throughout', 'seemed', 'using', 'with',
                    'through', 'fifty', 'thru', 'anyone', 'doing', 'four', 'top', 'least', 'from', 'none', 'above',
                    'made', 're', 'themselves', 'than', 'were', 'might', 'just', 'once', 'must', 'else', 'one',
                    'serious', 'eleven', 'itself', 'beforehand', 'her', 'rather', 'take', 'ourselves', 'beyond',
                    'anyway', 'around', 'no', 'did', 'your', '’d', 'then', 'they', 'due', 'since', 'these', 'may',
                    "'ve", 'somewhere', 'whether', 'regarding', 'whereafter', 'mostly', 'will', '‘s', 'wherein',
                    'sixty', 'n’t', 'if', 'though', 'yet', 'up', 'name', 'seeming', 'was', 'always', 'or', 'those',
                    'ten', 'am', 'about', 'give', 'something', 'third', 'not', 'our', 'until', 'someone', 'everything',
                    'still', 'twenty', 'anything', 'become', 'an', 'thence', 'indeed', 'any', 'before', 'him', 'full',
                    'had', 'herself', 'therefore', 'thus', 'two', 'within', 'can', 'eight', 'five', 'alone', 'which',
                    'side', 'hereupon', 'that', 'whither', 'otherwise', "n't", 'most', 'his', 'except', 'while',
                    'below', 'as', 'for', 'although', 'also', '’s', 'meanwhile', 'afterwards', 'move', '’ve', 'over',
                    '‘re', 'say', 'during', 'namely', 'across', 'whatever', "'s", 'here', 'only', 'various', 'each',
                    'whoever', 'now', 'other', 'would', 'all', 'next', 'often', 'done', 'she', '’ll', 'we', 'upon',
                    'front', 'well', 'out', 'us', 'whose', 'via', 'have', 'after', 'ours', 'toward', 'seems', '’m',
                    'has', "'re", 'forty', 'between', '‘d', 'could', 'down', 'among', 'is', 'others', 'somehow',
                    'being', 'such', 'yours', 'anywhere', 'do', 'to', 'whereas', 'their', 'whereby', 'my', 'onto',
                    'perhaps', 'yourselves', 'few', '‘ve', 'whereupon', 'really', 'behind', 'thereby', 'who', 'became',
                    'nobody', 'moreover', 'hundred', '‘ll', 'and', 'because', 'go', 'them', 'six', 'unless', 'never',
                    'everyone', 'sometime', 'noone', 'me', 'sometimes', 'thereupon', 'per', 'when', 'everywhere',
                    'hers', 'twelve', 'by', 'ca', 'very', 'another', 'on', 'seem', 'own', 'too', 'bottom', 'without',
                    'becoming', 'used', 'but', 'more', 'amongst', 'amount', 'neither', 'much', 'keep', 'besides',
                    'back', 'either', 'further', 'how', 'yourself', 'towards', 'put', 'several', 'why', 'whence', 'off',
                    'along', 'together', 'nowhere', 'thereafter', 'show', '‘m', 'make', 'latterly', 'does', 'wherever',
                    'some', 'elsewhere', 'it', 'this', 'in', 'are', 'even', 'again', 'where', 'whenever', '’re', 'nine',
                    'the', 'fifteen', 'becomes', 'last', 'formerly', 'he', 'many', 'quite', 'almost', 'so', 'into',
                    'part', 'see'}

stop_words_sklearn = {"a", "about", "above", "across", "after", "afterwards", "again", "against",
                      "all", "almost", "alone", "along", "already", "also", "although", "always",
                      "am", "among", "amongst", "amoungst", "amount", "an", "and", "another",
                      "any", "anyhow", "anyone", "anything", "anyway", "anywhere", "are",
                      "around", "as", "at", "back", "be", "became", "because", "become",
                      "becomes", "becoming", "been", "before", "beforehand", "behind", "being",
                      "below", "beside", "besides", "between", "beyond", "bill", "both",
                      "bottom", "but", "by", "call", "can", "cannot", "cant", "co", "con",
                      "could", "couldnt", "cry", "de", "describe", "detail", "do", "done",
                      "down", "due", "during", "each", "eg", "eight", "either", "eleven", "else",
                      "elsewhere", "empty", "enough", "etc", "even", "ever", "every", "everyone",
                      "everything", "everywhere", "except", "few", "fifteen", "fifty", "fill",
                      "find", "fire", "first", "five", "for", "former", "formerly", "forty",
                      "found", "four", "from", "front", "full", "further", "get", "give", "go",
                      "had", "has", "hasnt", "have", "he", "hence", "her", "here", "hereafter",
                      "hereby", "herein", "hereupon", "hers", "herself", "him", "himself", "his",
                      "how", "however", "hundred", "i", "ie", "if", "in", "inc", "indeed",
                      "interest", "into", "is", "it", "its", "itself", "keep", "last", "latter",
                      "latterly", "least", "less", "ltd", "made", "many", "may", "me",
                      "meanwhile", "might", "mill", "mine", "more", "moreover", "most", "mostly",
                      "move", "much", "must", "my", "myself", "name", "namely", "neither",
                      "never", "nevertheless", "next", "nine", "no", "nobody", "none", "noone",
                      "nor", "not", "nothing", "now", "nowhere", "of", "off", "often", "on",
                      "once", "one", "only", "onto", "or", "other", "others", "otherwise", "our",
                      "ours", "ourselves", "out", "over", "own", "part", "per", "perhaps",
                      "please", "put", "rather", "re", "same", "see", "seem", "seemed",
                      "seeming", "seems", "serious", "several", "she", "should", "show", "side",
                      "since", "sincere", "six", "sixty", "so", "some", "somehow", "someone",
                      "something", "sometime", "sometimes", "somewhere", "still", "such",
                      "system", "take", "ten", "than", "that", "the", "their", "them",
                      "themselves", "then", "thence", "there", "thereafter", "thereby",
                      "therefore", "therein", "thereupon", "these", "they", "thick", "thin",
                      "third", "this", "those", "though", "three", "through", "throughout",
                      "thru", "thus", "to", "together", "too", "top", "toward", "towards",
                      "twelve", "twenty", "two", "un", "under", "until", "up", "upon", "us",
                      "very", "via", "was", "we", "well", "were", "what", "whatever", "when",
                      "whence", "whenever", "where", "whereafter", "whereas", "whereby",
                      "wherein", "whereupon", "wherever", "whether", "which", "while", "whither",
                      "who", "whoever", "whole", "whom", "whose", "why", "will", "with",
                      "within", "without", "would", "yet", "you", "your", "yours", "yourself",
                      "yourselves"}

STOP_WORDS = stop_words_nltk.union(stop_words_spacy).union(stop_words_sklearn)
STOP_WORDS = STOP_WORDS.difference({'not'})
STOP_WORDS = STOP_WORDS.union({'-PRON-'})

# https://en.wikipedia.org/wiki/Interrogative_word
QUESTION_WORDS = {"who", "whom", "whose", "what", "when", "where", "why", "how",
                  "there", "that", "which", "whose", "whither", "whence", "whether", "whatsoever"}
STOP_WORDS = STOP_WORDS.difference(QUESTION_WORDS)
